# AppVeyor file
# http://www.appveyor.com/docs/appveyor-yml

# Build version format
version: "{build}"

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

# Scripts that are called at very beginning, before repo cloning
init:
  # Fix line endings on Windows
  - git config --global core.autocrlf true

# Test against this version of Node.js
environment:
  nodejs_version: "8.11"
  SAUCE_USERNAME:
    secure: urRYP9EQoRpDVcREo1HoNA==
  SAUCE_ACCESS_KEY:
    secure: 34SrDTIXrCWkakMDBCSyEGCWUStBJcbimW0gGnWF7I3zMXRwbetSZO9bHTmT98H2
  COVERALLS_REPO_TOKEN: "VC97qTfg9RO9TCP7Gqyq8oTlDjvBG8RIC"

build: off

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn

before_test:

test_script:
  - if "%APPVEYOR_SCHEDULED_BUILD%" == "True" (
      yarn test:sauce &&
      yarn check:third-party
    ) else (
      yarn test
    )

on_success:
  - yarn coveralls
  - 7z a -tzip coverage.zip coverage
  - curl --silent --upload-file coverage.zip https://transfer.sh/coverage.zip

notifications:
  - provider: Email
    to:
      - limon.monte@gmail.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true

# Preserve node_modules between builds
cache: node_modules -> yarn.lock
