language: node_js
dist: xenial
node_js: lts/*
sudo: true

addons:
  firefox: latest
  chrome: stable

# limit the Travis 'build on push' feature to master and dist branches only
branches:
  only:
   - master
   - dist

install:
  - yarn install
  - yarn build

  # bundlesize
  - yarn global add bundlesize
  - bundlesize -f dist/sweetalert2.all.min.js -s 16kB

script:
  # xvfb-run is needed for headless testing with real browsers
  - if [[ "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      xvfb-run yarn check;
    fi;

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      travis_retry yarn check:sauce &&
      yarn check:third-party;
    fi;

notifications:
  email:
    on_success: never

after_success:
  # update the dist branch to trigger the "release" task
  - if [[ "$TRAVIS_BRANCH" = "master" ]]; then
      node tools/merge-master-into-dist;
    fi;
  - yarn release;
  - if [[ "$TRAVIS_BRANCH" != "dist" && "$TRAVIS_EVENT_TYPE" != "cron" ]]; then
      cat ./coverage/lcov.info | coveralls;
      zip -r coverage.zip coverage;
      curl --upload-file ./coverage.zip https://transfer.sh/coverage.zip;
    fi;
